<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-CO3L4UM" ignored="0" name="Test1" tests="7" failures="1" timestamp="25 May 2019 08:01:10 GMT" time="0.051" errors="0">
  <testcase name="test2" time="0.009" classname="org.testNG.TestNG.Annotations2"/>
  <testcase name="test1" time="0.011" classname="org.testNG.TestNG.Annotations2">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="org.testNG.TestNG.Annotations2">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="org.testNG.TestNG.Annotations2">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.002" classname="org.testNG.TestNG.Annotations2">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="org.testNG.TestNG.Annotations2">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase name="test1" time="0.001" classname="org.testNG.TestNG.Annotations2">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at org.testNG.TestNG.Annotations2.test1(Annotations2.java:19)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test1 -->
